// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwxHwufBNNdXHXW6WvzWOY2leDeOcFa-Q',
    appId: '1:175835918560:web:90dbb783d9b8ca7bbba085',
    messagingSenderId: '175835918560',
    projectId: 'chat-app-4c902',
    authDomain: 'chat-app-4c902.firebaseapp.com',
    storageBucket: 'chat-app-4c902.appspot.com',
    measurementId: 'G-WDK13WQVG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAERafnVtt5_9__4iiO6imIQTzJ2lENcao',
    appId: '1:175835918560:android:04dddd1b77c6b892bba085',
    messagingSenderId: '175835918560',
    projectId: 'chat-app-4c902',
    storageBucket: 'chat-app-4c902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKZLc_mGUYQytv1ZkVveddIzTSmu0ywSg',
    appId: '1:175835918560:ios:c89cf5b0b81ecee2bba085',
    messagingSenderId: '175835918560',
    projectId: 'chat-app-4c902',
    storageBucket: 'chat-app-4c902.appspot.com',
    iosClientId: '175835918560-msneiqin4k8v8fqqfck5aeoab1gncals.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappFirebase',
  );
}
